# Generated by Django 6.0.5 on 2026-05-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_quantity_alter_book_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
