# Generated by Django 6.0.5 on 2026-05-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='total_borrowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='column',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='row',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
