# Generated by Django 6.0.5 on 2026-05-24 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_studentprofile_total_borrowed_alter_book_column_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='issue_time',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_borrowed',
        ),
        migrations.AddField(
            model_name='bookissue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pin',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
