# Generated by Django 6.0.5 on 2026-05-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_bookissue_issue_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookissue',
            old_name='issue_date',
            new_name='issued_at',
        ),
        migrations.RemoveField(
            model_name='bookissue',
            name='returned',
        ),
        migrations.AlterField(
            model_name='book',
            name='column',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='row',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pin',
            field=models.CharField(max_length=10),
        ),
    ]
