# Generated by Django 6.0.5 on 2026-05-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_rename_issue_date_bookissue_issued_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
