# Generated by Django 6.0.5 on 2026-05-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_bookissue_returned_bookissue_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='due_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='due_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='due_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookissue',
            name='due_return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
