# Generated by Django 6.0.5 on 2026-05-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
    ]
